name: Countdown Tests and Linting

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify your Python version here

      - name: Install dependencies
        run: pip install -r project2/requirements.txt  # Replace with your requirements file if needed

      - name: Run tests
        run: python project2/test_countdown.py

      - name: Run linters
        run: python project2/lint_countdown.py

      - name: Create Issue with test and lint results
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Test and Lint Results
          content-filepath: |
            project2/test_results.txt
            project2/lint_results.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

