name: Countdown Tests and Linting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify your Python version here

      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with your requirements file if needed

      - name: Run tests
        id: test
        run: python test_countdown.py
        continue-on-error: true

      - name: Run linters
        id: lint
        run: python lint_countdown.py
        continue-on-error: true

      - name: Create Issue on Test Failure
        if: steps.test.outcome != 'success'
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.create({
              repo: context.repo.repo,
              owner: context.repo.owner,
              title: 'There is an error in test',
              body: 'There was a failure in the test. Please check the logs for details.'
            })

      - name: Create Issue on Linter Failure
        if: steps.lint.outcome != 'success'
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.create({
              repo: context.repo.repo,
              owner: context.repo.owner,
              title: 'There is an error in linter',
              body: 'There was a failure in the linter. Please check the logs for details.'
            })
